// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuAok8q9ya9uOw2EcgR8Yl4ce2HhtBRXM',
    appId: '1:864184414803:web:5fd3d98710f1fc1dbb4ca6',
    messagingSenderId: '864184414803',
    projectId: 'orionchat-flutter',
    authDomain: 'orionchat-flutter.firebaseapp.com',
    storageBucket: 'orionchat-flutter.appspot.com',
    measurementId: 'G-HFNWDT5RL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl839i6kr2pIDFwkGnaqFJxZQXEBs4LwY',
    appId: '1:864184414803:android:f927ea386853324fbb4ca6',
    messagingSenderId: '864184414803',
    projectId: 'orionchat-flutter',
    storageBucket: 'orionchat-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0qcp-_x7tbJyTHW59pDbp062_05z1Vc',
    appId: '1:864184414803:ios:2ab3a9efdf364f65bb4ca6',
    messagingSenderId: '864184414803',
    projectId: 'orionchat-flutter',
    storageBucket: 'orionchat-flutter.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0qcp-_x7tbJyTHW59pDbp062_05z1Vc',
    appId: '1:864184414803:ios:ad1eb4fc73b6b3c8bb4ca6',
    messagingSenderId: '864184414803',
    projectId: 'orionchat-flutter',
    storageBucket: 'orionchat-flutter.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
